image: nikolaik/python-nodejs

services:
  - nouchka/sqlite3

before_script:
  - cd ./frontend
  - npm run build
  - pip install -r requirements.txt
  - python ./manage.py makemigrations
  - python ./manage.py migrate

test:
  script: 
    - python ./manage.py test
