image: python:3.7.6-buster

services:
  - nouchka/sqlite3

include:
  - template: License-Scanning.gitlab-ci.yml

before_script:
  - pip install -r requirements.txt
  - python ./manage.py makemigrations
  - python ./manage.py migrate

test:
  script: 
    - python ./manage.py test