image: python:3.7.6-buster

services:
  - nouchka/sqlite3

include:
  - template: License-Scanning.gitlab-ci.yml

variables:
  LM_PYTHON_VERSION: 3.8

before_script:
  - pip install -r requirements.txt
  - python ./manage.py makemigrations
  - python ./manage.py migrate

test:
  script: 
    - python ./manage.py test