image: nikolaik/python-nodejs:python3.5-nodejs14

services:
  - nouchka/sqlite3

before_script:
  - cd ./frontend
  - npm i
  - npm run build
  - cd ../
  - pip install -r requirements.txt
  - python ./manage.py makemigrations
  - python ./manage.py migrate

test:
  script:
    - python ./manage.py test
