#import "./ApplicationSmallFragment.gql"
#import "./ApplicationImageFragment.gql"
#import "../../User/Fragment/UserFullFragment.gql"
#import "../Product/ProductFragment.gql"

fragment ApplicationFullFragment on ApplicationType {
  ...ApplicationSmallFragment
  description
  images {
    ...ApplicationImageFragment
  }
  admins
  members
  products {
    edges {
      node {
        ...ProductFragment
      }
    }
  }
}
