#import "../../User/Fragment/UserFullFragment.gql"

fragment CitrusOrderFragment on CitrusOrderType {
    id
    user {
        ...UserFullFragment
    }
    sendMail
    amounts {
        edges {
            node {
                id
                amount
                product {
                    id
                    name
                    price
                }
            }
        }
    }
}