mutation orderAdd($sendMail: Boolean!, $amounts: [CreateCitrusAmountInput]!) {
    addCitrusOrder(input: { sendMail: $sendMail, amountsAdd: $amounts }) {
        citrusOrder {
            id
        }
    }
}