#import "./Fragment/ApplicationFullFragment.gql"

mutation applicationUpdate($id: ID!, $name: String!, $description: String!) {
  updateApplication(
    id: $id
    input: {name: $name, description: $description }
  ) {
    application {
      ...ApplicationFullFragment
    }
  }
}
