#import "./ApplicationFragment.gql"
#import "./Product/ProductFragment.gql"

query ApplicationBySlug($slug: String!) {
  applicationBySlug(slug: $slug) {
    ...ApplicationFragment
    description
    images {
      alt
      image
    }
    products {
      edges {
        node {
          ...ProductFragment
        }
      }
    }
  }
}
