#import "../User/Fragment/UserFullFragment.gql"

fragment ArticleFragment on ArticleType {
  id
  title
  content
  dateCreation
  category {
    id
    name
  }
  author {
    ...UserFullFragment
  }
}