#import "./Fragment/UserFullFragment.gql"

query UserCurrent {
  user {
    ...UserFullFragment
    isSuperuser
    userPermissions {
      codename
      contentType {
        model
      }
    }
    groups {
      id
      name
    }
  }
}
