#import "./Fragment/UserFullFragment.gql"

mutation UserLogin($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    user {
      ...UserFullFragment
      isSuperuser
      userPermissions {
        codename
        contentType {
          appLabel
        }
      }
      groups {
        id
        name
      }
    }
  }
}
