#import "./ProductFragment.gql"

query ProductByApplicationSlug($application: String!) {
  allProduct(application_Slug: $application) {
    edges {
      node {
        ...ProductFragement
      }
    }
  }
}
